<a href="https://colab.research.google.com/github/matthewpecsok/4482_fall_2026/blob/main/labs/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setups

In [ ]:
import pandas as pd
import numpy as np

import os

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.naive_bayes import GaussianNB

import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

from sklearn import metrics

In [ ]:
titanic = pd.read_csv("https://raw.githubusercontent.com/matthewpecsok/4482_fall_2026/main/data/titanic_cleaned.csv")

In [ ]:
titanic['Age_lt_10'] =  titanic['Age']<10

In [ ]:
titanic.Age_lt_10.value_counts()

False    652
True      62
Name: Age_lt_10, dtype: int64

In [ ]:
titanic['Fare_lt_50'] =  titanic['Fare']<50

In [ ]:
titanic.Fare_lt_50.value_counts()

True     576
False    138
Name: Fare_lt_50, dtype: int64

# Lab Answers

In [ ]:
titanic.Survived.value_counts(normalize=True)

0    0.593838
1    0.406162
Name: Survived, dtype: float64

In [ ]:
# proportions by fare. lt = less than
ct = pd.crosstab(titanic['Fare_lt_50'], titanic['Survived'])
ct.div(ct.sum(axis=0), axis=1)

Survived          0         1
Fare_lt_50
False       0.09434  0.337931
True        0.90566  0.662069

In [ ]:
# proportions by age. lt = less than
ct = pd.crosstab(titanic['Age_lt_10'], titanic['Survived'])
ct.div(ct.sum(axis=0), axis=1)

Survived          0         1
Age_lt_10
False      0.943396  0.868966
True       0.056604  0.131034